# Deployment
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: http-server
  namespace: azhuox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
        - name: simple-http-server
          image: python:2.7
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["-c", "echo \"<p>Hello from $(hostname)</p>\" > index.html; python -m SimpleHTTPServer 80"]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 25m
              memory: 25Mi
            limits:
              cpu: 50m
              memory: 50Mi
        - name: busybox
          image: alpine:3.10
          command: ['sh', '-c', 'while true; do sleep 60; done']
          resources:
            requests:
              cpu: 25m
              memory: 25Mi
            limits:
              cpu: 50m
              memory: 50Mi
---


# Internal service
kind: Service
apiVersion: v1
metadata:
  name: http-server-int-service
  namespace: azhuox
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: http-server


